forms/forms/urls.py
from django.contrib import admin
from django.urls import path
from formsapp import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('formsapp/',include('formsapp.urls')),
]

forms/formsapp/urls.py
# from django.conf.urls import url
from formsapp import views
from django.urls import path


# template tagging
app_name='formsapp'

urlpatterns = [
    path('forms',views.contact_view,name='forms'),
    path('other',views.other,name='other'),
]

forms/formsapp/models.py
from django.db import models

# Create your models here.

forms/forms/asgi.py
"""
ASGI config for forms project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'forms.settings')

application = get_asgi_application()

forms/forms/settings.py
"""
Django settings for forms project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR=os.path.join(BASE_DIR,'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4#9-=j-!!caz9h&4q+^)-^=#*_&@j+%46i6xq$6_ptruz$3$@t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'formsapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

forms/forms/wsgi.py
"""
WSGI config for forms project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'forms.settings')

application = get_wsgi_application()

forms/formsapp/forms.py
from django import forms
from django.core import validators
class ContactForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    text=forms.CharField(widget=forms.Textarea)

    botcatcher=forms.CharField(required=False,widget=forms.HiddenInput,
                               validators=[validators.MaxLengthValidator(0)])

    # def clean_botcatcher(self):
    #     botcatcher=self.cleaned_data['botcatcher']
    #     if len(botcatcher)>0:
    #         raise forms.ValidationError("bot caught")
    #     return botcatcher 
        # instead of all this function we can use inbuilt validator. 

forms/formsapp/views.py
from django.shortcuts import render

# Create your views here.
from . import forms

def index(request):
    return render(request,'formsapp/index.html')

def other(request):
    return render(request,'formsapp/other.html')

def contact_view(request):
    form=forms.ContactForm()

    if request.method=='POST':
        form=forms.ContactForm(request.POST)

        if form.is_valid():
            # do something code
            print("valid")

    return render(request,'formsapp/forms.html',{'form':form})

forms/templates/formsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=  , initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
      <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'formsapp:other' %}">Other</a></li>
                </ul>
            </div>
      </nav>

      <div class="container">
        {%block body_block%}

        {%endblock%}
      </div>
</body>
</html>

forms/templates/formsapp/forms.html
<!DOCTYPE html>

{%extends "formsapp/base.html"%}

{%block body_block%}
        <form method="POST">
            {{form.as_p}}
            {%csrf_token%}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
{%endblock%}

forms/templates/formsapp/index.html
<!DOCTYPE html>
{%extends "formsapp/base.html"%}

{%block body_block%}
    <h1>welcome to home page!</h1>
{%endblock%}

forms/templates/formsapp/other.html
<!DOCTYPE html>

{%extends "formsapp/base.html"%}

{%block body_block%}
    <h1>welcome to other!</h1>
    <a href="{% url 'formsapp:forms' %}">Contact page</a><br>
    <!-- <a href="{% url 'admin:index' %}">Link to admin</a><br>
    <a href="{% url 'index' %}">Link to index</a><br> -->
{%endblock%}